-- chat 테이블 생성 (채팅 메시지 저장)
CREATE TABLE public.chat (
	id int8 GENERATED BY DEFAULT AS IDENTITY(
		INCREMENT BY 1 
		MINVALUE 1 
		MAXVALUE 9223372036854775807 
		START 1 
		CACHE 1 
		NO CYCLE
	) NOT NULL,
	message_text text NOT NULL,
	sender varchar(20) NOT NULL,
	created_at timestamp(6) NOT NULL,
	jobseeker_id int8 NULL,
	session_id varchar(255) NULL,
	CONSTRAINT chat_pkey PRIMARY KEY (id),
	CONSTRAINT chat_sender_check CHECK (
		((sender)::text = ANY ((ARRAY['user'::character varying, 'bot'::character varying])::text[]))
	),
	CONSTRAINT fk_chat_jobseeker FOREIGN KEY (jobseeker_id) 
		REFERENCES public.jobseeker_profiles(id) 
		ON DELETE CASCADE
);

-- 인덱스 생성 (성능 최적화)
CREATE INDEX idx_chat_jobseeker_id ON public.chat USING btree (jobseeker_id);
CREATE INDEX idx_chat_session_id ON public.chat USING btree (session_id);
CREATE INDEX idx_chat_created_at ON public.chat USING btree (created_at DESC);

-- 코멘트 추가
COMMENT ON TABLE public.chat IS '챗봇 대화 내역';
COMMENT ON COLUMN public.chat.id IS '메시지 ID';
COMMENT ON COLUMN public.chat.message_text IS '메시지 내용';
COMMENT ON COLUMN public.chat.sender IS '발신자 (user: 사용자, bot: 챗봇)';
COMMENT ON COLUMN public.chat.created_at IS '메시지 생성 시간';
COMMENT ON COLUMN public.chat.jobseeker_id IS '구직자 ID (jobseeker_profiles 참조)';
COMMENT ON COLUMN public.chat.session_id IS '세션 ID (대화 세션 그룹화)';
